server:
  port: ${BACKEND_SERVER_PORT:6688} # 本服务器启动的端口号
  servlet:
    encoding:
      force: true
spring:
  # 配置文件上传限制
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
mybatis-plus:
  mapper-locations: classpath*:com/simplefanc/voj/backend/mapper/xml/**Mapper.xml
  type-aliases-package: com.simplefanc.voj.common.pojo.entity
  configuration:
    cache-enabled: false
  # 关闭打印 mybatis-plus 的 LOGO
  global-config:
    banner: false

# 消费者将要去访问的微服务名称（注册成功进入nacos的微服务提供者）
service-url:
  name: voj-judger # 服务名

filepath:
  user-avatar-folder: "/voj/file/avatar"
  home-carousel-folder: "/voj/file/carousel"
  markdown-file-folder: "/voj/file/md"
  problem-file-folder: "/voj/file/problem"
  contest-text-print-folder: "/voj/file/contest_print"
  img-api: "/api/public/img/"
  file-api: "/api/public/file/"
  testcase-base-folder: "/voj/testcase"
  testcase-tmp-folder: "/voj/file/zip"
  file-download-tmp-folder: "/voj/file/zip/download"
  contest-ac-submission-tmp-folder: "/voj/file/zip/contest_ac"

voj:
  remote:
    ojs:
      - oj: JSK
        accounts:
          - username: "+8615079084006"
            password: 123456ecnu
          - username: "+8615294203791"
            password: 123456ecnu
          - username: "+8613872879909"
            password: 123456ecnu
          - username: "+8615527863968"
            password: 123456ecnu
          - username: "+8615271344215"
            password: 123456ecnu
          - username: "+8613387649790"
            password: 123456ecnu
      - oj: MXT
        accounts:
          - username: ecnuv1@163.com
            password: 123456ecnu
          - username: ecnuv2@163.com
            password: 123456ecnu
          - username: ecnuv3@163.com
            password: 123456ecnu
          - username: ecnuv4@163.com
            password: 123456ecnu
          - username: ecnuv5@163.com
            password: 123456ecnu
          - username: ecnuv6@163.com
            password: 123456ecnu
          - username: ecnuv7@163.com
            password: 123456ecnu
          - username: ecnuv8@163.com
            password: 123456ecnu
      - oj: HDU
        accounts:
          - username: ecnuv1
            password: 123456ecnu
          - username: ecnuv2
            password: 123456ecnu
      - oj: POJ
        accounts:
          - username: jianghuchuan
            password: 123456ecnu
          - username: maolilan
            password: 123456ecnu
          - username: aliboshi
            password: 123456ecnu
      - oj: TKOJ
        accounts:
          - username: ecnuv2
            password: 123456ecnu
          - username: fruitshampoo
            password: 123456ecnu
          - username: 11204902153
            password: 123456ecnu
          - username: onz11223
            password: 123456ecnu
          - username: jianghuchuan
            password: 123456ecnu
          - username: maolilan
            password: 123456ecnu